services:
    sa-backend:
        container_name: sa-backend
        image: sa-backend:0.0.1
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "${PORT_OUT}:8080"
        restart: always
        depends_on:
            - postgres
        environment:
            SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
            CLIENT_HOST: ${CLIENT_HOST}
            RDS_HOSTNAME: ${RDS_HOSTNAME}
            RDS_USERNAME: ${RDS_USERNAME}
            RDS_PORT: 5432
            RDS_DB_NAME: ${RDS_DB_NAME}
            RDS_PASSWORD: ${RDS_PASSWORD}
            JWT_SECRET: ${JWT_SECRET}
            FILE_PATH: ${FILE_PATH}
        networks:
            - sa-network
        volumes:
            - "filePath:${FILE_PATH}"
    postgres:
        container_name: postgres
        image: 'postgres:15.4-alpine'
        ports:
            - "5432:5432"
        restart: always
        environment:
            POSTGRES_USER: ${RDS_HOSTNAME}
            PGDATA: /var/lib/postgresql/data/pgdata
            POSTGRES_DB: ${RDS_DB_NAME}
            POSTGRES_PASSWORD: ${RDS_PASSWORD}
        volumes:
            - /var/sa-backend/postgresql/data:/var/lib/postgresql/data/pgdata
        networks:
            - sa-network
# Volumes

networks:
    sa-network:
volumes:
    filePath:
        driver: local
        driver_opts:
            type: none
            device: $FILE_PATH
            o: bind
        external: false
