services:
    sa-backend:
        container_name: sa-backend
        image: sa-backend:0.0.1
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "${PORT_OUT}:8080"
        restart: always
        depends_on:
            - postgres
        environment:
            SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
            RDS_HOSTNAME: postgres
            RDS_PORT: 5432
            RDS_DB_NAME: ${RDS_DB_NAME}
            RDS_USERNAME: ${RDS_USERNAME}
            RDS_PASSWORD: ${RDS_PASSWORD}
        networks:
            - sa-network
        volumes:
            - "filePath:/opt/files/"
    postgres:
        container_name: postgres
        image: 'postgres:latest'
        ports:
            - "5432:5432"
        restart: always
        environment:
            POSTGRES_USER: postgres
            PGDATA: /var/lib/postgresql/data/pgdat
            POSTGRES_DB: self_assessment_educational_programs_storage
            POSTGRES_PASSWORD: ${RDS_PASSWORD}
        volumes:
            - /var/hub-back/postgresql/data:/var/lib/postgresql/data/pgdat
        networks:
            - sa-network
# Volumes

networks:
    sa-network:
volumes:
    filePath:
        driver: local
        driver_opts:
            type: none
            device: $FILE_PATH
            o: bind
        external: false
