
CREATE TABLE auth_group

    id         UUID                        NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    deleted    BOOLEAN                     NOT NULL DEFAULT FALSE,
    name       VARCHAR(150)                NOT NULL,
    CONSTRAINT pk_auth_group PRIMARY KEY (id)
);

CREATE TABLE auth_group_permissions
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    group_id      INTEGER                                 NOT NULL,
    permission_id INTEGER                                 NOT NULL,
    CONSTRAINT pk_auth_group_permissions PRIMARY KEY (id)
);

CREATE TABLE auth_permission
(
    id         UUID                        NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    deleted    BOOLEAN                     NOT NULL DEFAULT FALSE,
    name       VARCHAR(255)                NOT NULL,
    codename   VARCHAR(100)                NOT NULL,
    CONSTRAINT pk_auth_permission PRIMARY KEY (id)
);

CREATE TABLE authtoken_token
(
    key     VARCHAR(40)              NOT NULL,
    created TIMESTAMP with time zone NOT NULL,
    user_id BIGINT                   NOT NULL,
    CONSTRAINT pk_authtoken_token PRIMARY KEY (key)
);

CREATE TABLE control_measures_and_academic_integrity
(
    id                                                   UUID                        NOT NULL,
    created_at                                           TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at                                           TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    deleted                                              BOOLEAN                     NOT NULL DEFAULT FALSE,
    description                                          TEXT                        NOT NULL,
    clarity_criteria                                     TEXT                        NOT NULL,
    information_provision                                TEXT                        NOT NULL,
    compliance_requirements                              TEXT                        NOT NULL,
    accessibility_certification_procedure                TEXT                        NOT NULL,
    objectivity_procedures                               TEXT                        NOT NULL,
    repeating_control_measures_procedures                TEXT                        NOT NULL,
    appeal_procedure_and_results_of_control_measures     TEXT                        NOT NULL,
    policies_and_standards_documents                     TEXT                        NOT NULL,
    combating_violations_of_academic_integrity_solutions TEXT                        NOT NULL,
    promoting_academic_integrity                         TEXT                        NOT NULL,
    responding_to_violations_of_academic_integrity       TEXT                        NOT NULL,
    CONSTRAINT pk_control_measures_and_academic_integrity PRIMARY KEY (id)
);

CREATE TABLE education_program
(
    id                   UUID                        NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at           TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    deleted              BOOLEAN                     NOT NULL DEFAULT FALSE,
    education_program_id BIGINT                      NOT NULL,
    name                 VARCHAR(250)                NOT NULL,
    level                VARCHAR(20)                 NOT NULL,
    CONSTRAINT pk_education_program PRIMARY KEY (id)
);

CREATE TABLE education_program_accreditation_information
(
    id                                UUID                        NOT NULL,
    created_at                        TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at                        TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    deleted                           BOOLEAN                     NOT NULL DEFAULT FALSE,
    specialty_licensing_info          VARCHAR(250)                NOT NULL,
    cycle                             VARCHAR(250)                NOT NULL,
    specialization                    VARCHAR(250),
    program_type                      VARCHAR(250)                NOT NULL,
    admission_degree                  VARCHAR(250)                NOT NULL,
    duration                          VARCHAR(255)                NOT NULL,
    education_program_forms           VARCHAR(255)                NOT NULL,
    location                          VARCHAR(255)                NOT NULL,
    grants_professional_qualification VARCHAR(255)                NOT NULL,
    professional_qualification        VARCHAR(255),
    guarantee_id                      BIGINT                      NOT NULL,
    guarantee_position                VARCHAR(255)                NOT NULL,
    guarantee_email                   VARCHAR(254)                NOT NULL,
    guarantee_phone                   VARCHAR(20)                 NOT NULL,
    additional_phone                  VARCHAR(20),
    education_program_id              UUID                        NOT NULL,
    field_of_study_id                 UUID                        NOT NULL,
    guarantee_full_name_id            UUID                        NOT NULL,
    specialty_id                      UUID                        NOT NULL,
    subdivision_id                    UUID                        NOT NULL,
    CONSTRAINT pk_education_program_accreditation_information PRIMARY KEY (id)
);

CREATE TABLE education_program_accreditation_information_language_of
(
    education_program_accreditation_information_id UUID NOT NULL,
    languages_id                                   UUID NOT NULL,
    CONSTRAINT pk_education_program_accreditation_information_languages PRIMARY KEY (education_program_accreditation_information_id, languages_id)
);

CREATE TABLE education_program_accreditation_information_other_education
(
    education_program_accreditation_information_id UUID NOT NULL,
    subdivisions_id                                UUID NOT NULL,
    CONSTRAINT pk_education_program_accreditation_information_subdivisions PRIMARY KEY (education_program_accreditation_information_id, subdivisions_id)
);

CREATE TABLE education_program_design
(
    id                                       UUID                        NOT NULL,
    created_at                               TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at                               TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    deleted                                  BOOLEAN                     NOT NULL DEFAULT FALSE,
    goals                                    TEXT                        NOT NULL,
    uniqueness                               TEXT                        NOT NULL,
    stakeholder_student                      TEXT                        NOT NULL,
    stakeholder_employer                     TEXT                        NOT NULL,
    stakeholder_academic                     TEXT                        NOT NULL,
    stakeholder_other                        TEXT                        NOT NULL,
    market_trends                            TEXT                        NOT NULL,
    industry_and_regional_context            TEXT                        NOT NULL,
    domestic_and_foreign_programs_experience TEXT                        NOT NULL,
    learning_experience_achieve              TEXT                        NOT NULL,
    national_qualifications_level            TEXT                        NOT NULL,
    CONSTRAINT pk_education_program_design PRIMARY KEY (id)
);

CREATE TABLE education_program_document
(
    id                     UUID                        NOT NULL,
    created_at             TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at             TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    deleted                BOOLEAN                     NOT NULL DEFAULT FALSE,
    general_information_id UUID                        NOT NULL,
    type                   VARCHAR(255)                NOT NULL,
    name                   VARCHAR(100)                NOT NULL,
    content                VARCHAR(100)                NOT NULL,
    path                   VARCHAR(100),
    CONSTRAINT pk_education_program_document PRIMARY KEY (id)
);

CREATE TABLE education_program_general_information
(
    id                      UUID                        NOT NULL,
    created_at              TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at              TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    deleted                 BOOLEAN                     NOT NULL DEFAULT FALSE,
    history_and_development TEXT                        NOT NULL,
    CONSTRAINT pk_education_program_general_information PRIMARY KEY (id)
);

CREATE TABLE education_statistics
(
    id                     UUID                        NOT NULL,
    created_at             TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at             TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    deleted                BOOLEAN                     NOT NULL DEFAULT FALSE,
    general_information_id UUID                        NOT NULL,
    study_course_year      VARCHAR(255)                NOT NULL,
    academic_year          VARCHAR(11)                 NOT NULL,
    enrollment             INTEGER                     NOT NULL,
    full_time              INTEGER                     NOT NULL,
    evening                INTEGER                     NOT NULL,
    part_time              INTEGER                     NOT NULL,
    foreign_full_time      INTEGER                     NOT NULL,
    foreign_evening        INTEGER                     NOT NULL,
    foreign_part_time      INTEGER                     NOT NULL,
    CONSTRAINT pk_education_statistics PRIMARY KEY (id)
);

CREATE TABLE educational_environment_and_material_resources
(
    id                                            UUID                        NOT NULL,
    created_at                                    TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at                                    TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    deleted                                       BOOLEAN                     NOT NULL DEFAULT FALSE,
    financial_resources                           TEXT                        NOT NULL,
    educational_environment                       TEXT                        NOT NULL,
    safety_measures                               TEXT                        NOT NULL,
    support_services                              TEXT                        NOT NULL,
    special_needs_people_education                TEXT                        NOT NULL,
    policy_and_procedures_for_conflict_resolution TEXT                        NOT NULL,
    CONSTRAINT pk_educational_environment_and_material_resources PRIMARY KEY (id)
);

CREATE TABLE educational_program
(
    id                                          UUID                        NOT NULL,
    created_at                                  TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at                                  TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    deleted                                     BOOLEAN                     NOT NULL DEFAULT FALSE,
    description                                 TEXT                        NOT NULL,
    research_preparation                        TEXT                        NOT NULL,
    teaching_preparation                        TEXT                        NOT NULL,
    supervisor_relevance                        TEXT                        NOT NULL,
    research_support                            TEXT                        NOT NULL,
    international_participation                 TEXT                        NOT NULL,
    research_projects_supervisors_participation TEXT                        NOT NULL,
    academic_integrity_practices                TEXT                        NOT NULL,
    academic_integrity_preventing_violations    TEXT                        NOT NULL,
    CONSTRAINT pk_educational_program PRIMARY KEY (id)
);

CREATE TABLE educational_program_access
(
    id                                             UUID                        NOT NULL,
    created_at                                     TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at                                     TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    deleted                                        BOOLEAN                     NOT NULL DEFAULT FALSE,
    admission_rules_link                           VARCHAR(200)                NOT NULL,
    admission_requirements                         TEXT                        NOT NULL,
    recognition_of_education_results_accessibility TEXT                        NOT NULL,
    admission_requirements_applying_rules_practice TEXT                        NOT NULL,
    recognition_of_education_results_doc           TEXT                        NOT NULL,
    education_results_doc_applying_rules_practice  TEXT                        NOT NULL,
    CONSTRAINT pk_educational_program_access PRIMARY KEY (id)
);

CREATE TABLE educational_program_learning_and_teaching
(
    id                            UUID                        NOT NULL,
    created_at                    TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at                    TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    deleted                       BOOLEAN                     NOT NULL DEFAULT FALSE,
    learning_and_teaching_methods TEXT                        NOT NULL,
    student_centered_approach     TEXT                        NOT NULL,
    academic_freedom              TEXT                        NOT NULL,
    learning_outcomes             TEXT                        NOT NULL,
    learning_and_research         TEXT                        NOT NULL,
    curriculum_update             TEXT                        NOT NULL,
    internationalization          TEXT                        NOT NULL,
    CONSTRAINT pk_educational_program_learning_and_teaching PRIMARY KEY (id)
);

CREATE TABLE educational_transparency_and_publicity
(
    id                        UUID                        NOT NULL,
    created_at                TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at                TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    deleted                   BOOLEAN                     NOT NULL DEFAULT FALSE,
    regulatory_documents      VARCHAR(1500)               NOT NULL,
    stakeholder_feedback_link VARCHAR(200)                NOT NULL,
    educational_program_link  VARCHAR(200)                NOT NULL,
    CONSTRAINT pk_educational_transparency_and_publicity PRIMARY KEY (id)
);

CREATE TABLE field_of_study
(
    id                  UUID                        NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at          TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    deleted             BOOLEAN                     NOT NULL DEFAULT FALSE,
    field_of_study_code INTEGER                     NOT NULL,
    field_of_study      VARCHAR(250)                NOT NULL,
    CONSTRAINT pk_field_of_study PRIMARY KEY (id)
);

CREATE TABLE general_information
(
    id                                                     UUID                        NOT NULL,
    created_at                                             TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at                                             TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    deleted                                                BOOLEAN                     NOT NULL DEFAULT FALSE,
    education_program_accreditation_information_id         UUID                        NOT NULL,
    education_program_general_information_id               UUID                        NOT NULL,
    hei_links_in_edebo_id                                  UUID                        NOT NULL,
    higher_education_institution_area_id                   UUID                        NOT NULL,
    higher_education_institution_information_id            UUID                        NOT NULL,
    self_assessment_educational_program_restricted_info_id UUID                        NOT NULL,
    CONSTRAINT pk_general_information PRIMARY KEY (id)
);

CREATE TABLE general_information_education_programs
(
    education_programs_id  UUID NOT NULL,
    general_information_id UUID NOT NULL,
    CONSTRAINT pk_general_information_educationprograms PRIMARY KEY (education_programs_id, general_information_id)
);

CREATE TABLE general_question_answer
(
    id                                                UUID                        NOT NULL,
    created_at                                        TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at                                        TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    deleted                                           BOOLEAN                     NOT NULL DEFAULT FALSE,
    control_measures_and_academic_integrity_id        UUID                        NOT NULL,
    educational_environment_and_material_resources_id UUID                        NOT NULL,
    educational_program_id                            UUID                        NOT NULL,
    educational_program_access_id                     UUID                        NOT NULL,
    educational_program_design_id                     UUID                        NOT NULL,
    educational_program_development_perspectives_id   UUID                        NOT NULL,
    educational_program_learning_and_teaching_id      UUID                        NOT NULL,
    educational_program_structure_and_content_id      UUID                        NOT NULL,
    educational_transparency_and_publicity_id         UUID                        NOT NULL,
    human_resources_id                                UUID                        NOT NULL,
    quality_assurance_id                              UUID                        NOT NULL,
    CONSTRAINT pk_general_question_answer PRIMARY KEY (id)
);

CREATE TABLE general_question_answer_educational_program_structure_n_content
(
    id                                    UUID                        NOT NULL,
    created_at                            TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at                            TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    deleted                               BOOLEAN                     NOT NULL DEFAULT FALSE,
    ep_credits_amount                     INTEGER                     NOT NULL,
    components_credits_amount             SMALLINT                    NOT NULL,
    student_electives_credits_amount      SMALLINT                    NOT NULL,
    content_compliance                    TEXT                        NOT NULL,
    individual_learning_path              TEXT                        NOT NULL,
    student_choice_right                  TEXT                        NOT NULL,
    student_practical_training            TEXT                        NOT NULL,
    student_soft_skills                   TEXT                        NOT NULL,
    relevant_professional_standard        TEXT                        NOT NULL,
    components_scope_correlating_approach TEXT                        NOT NULL,
    dual_form_education_structure         TEXT                        NOT NULL,
    CONSTRAINT pk_generalquestionanswereducationalprogramstructurencontent PRIMARY KEY (id)
);

CREATE TABLE hei_links_in_edebo
(
    id         UUID                        NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    deleted    BOOLEAN                     NOT NULL DEFAULT FALSE,
    website    VARCHAR(200)                NOT NULL,
    CONSTRAINT pk_hei_links_in_edebo PRIMARY KEY (id)
);

CREATE TABLE higher_education_institution_area
(
    id                             UUID                        NOT NULL,
    created_at                     TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at                     TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    deleted                        BOOLEAN                     NOT NULL DEFAULT FALSE,
    all_rooms                      BIGINT                      NOT NULL,
    own_rooms                      BIGINT                      NOT NULL,
    other_rights_rooms             BIGINT                      NOT NULL,
    rented_rooms                   BIGINT                      NOT NULL,
    educational_all_rooms          BIGINT                      NOT NULL,
    educational_own_rooms          BIGINT                      NOT NULL,
    educational_other_rights_rooms BIGINT                      NOT NULL,
    educational_rented_rooms       BIGINT                      NOT NULL,
    CONSTRAINT pk_higher_education_institution_area PRIMARY KEY (id)
);

CREATE TABLE higher_education_institution_information
(
    id         UUID                        NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    deleted    BOOLEAN                     NOT NULL DEFAULT FALSE,
    hei_id     UUID                        NOT NULL,
    ssu_id     UUID,
    CONSTRAINT pk_higher_education_institution_information PRIMARY KEY (id)
);

CREATE TABLE higher_educational_institution
(
    id                                  UUID                        NOT NULL,
    created_at                          TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at                          TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    deleted                             BOOLEAN                     NOT NULL DEFAULT FALSE,
    hei_id                              BIGINT                      NOT NULL,
    higher_educational_institution_name VARCHAR(250)                NOT NULL,
    institution_code                    BIGINT                      NOT NULL,
    website                             VARCHAR(200)                NOT NULL,
    head_full_name_id                   UUID                        NOT NULL,
    CONSTRAINT pk_higher_educational_institution PRIMARY KEY (id)
);

CREATE TABLE human_resources
(
    id                   UUID                        NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at           TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    deleted              BOOLEAN                     NOT NULL DEFAULT FALSE,
    competency_level     TEXT                        NOT NULL,
    employers_engagement TEXT                        NOT NULL,
    expert_involvement   TEXT                        NOT NULL,
    teacher_development  TEXT                        NOT NULL,
    teaching_excellence  TEXT                        NOT NULL,
    CONSTRAINT pk_human_resources PRIMARY KEY (id)
);

CREATE TABLE information_on_self_assessment_of_educational_program
(
    id                         UUID                        NOT NULL,
    created_at                 TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at                 TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    deleted                    BOOLEAN                     NOT NULL DEFAULT FALSE,
    general_information_id     UUID                        NOT NULL,
    general_question_answer_id UUID                        NOT NULL,
    tables_annex_id            UUID                        NOT NULL,
    CONSTRAINT pk_information_on_self_assessment_of_educational_program PRIMARY KEY (id)
);

CREATE TABLE language
(
    id         UUID                        NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    deleted    BOOLEAN                     NOT NULL DEFAULT FALSE,
    name       VARCHAR(50)                 NOT NULL,
    short_name VARCHAR(250)                NOT NULL,
    CONSTRAINT pk_language PRIMARY KEY (id)
);

CREATE TABLE op_development_perspectives
(
    id                 UUID                        NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at         TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    deleted            BOOLEAN                     NOT NULL DEFAULT FALSE,
    strong_weak_points TEXT                        NOT NULL,
    future_development TEXT                        NOT NULL,
    CONSTRAINT pk_op_development_perspectives PRIMARY KEY (id)
);

CREATE TABLE program_educational_components_information
(
    id                            UUID                        NOT NULL,
    created_at                    TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at                    TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    deleted                       BOOLEAN                     NOT NULL DEFAULT FALSE,
    component_name                VARCHAR(255)                NOT NULL,
    component_type                VARCHAR(255)                NOT NULL,
    syllabus                      VARCHAR(255),
    education_program_document_id UUID                        NOT NULL,
    special_equipment_info        TEXT                        NOT NULL,
    CONSTRAINT pk_program_educational_components_information PRIMARY KEY (id)
);

CREATE TABLE program_learning_outcome_correspondence_matrix
(
    id                       UUID                        NOT NULL,
    created_at               TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at               TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    deleted                  BOOLEAN                     NOT NULL DEFAULT FALSE,
    name                     TEXT                        NOT NULL,
    teaching_method          VARCHAR(1000)               NOT NULL,
    assessment_form          VARCHAR(200)                NOT NULL,
    educational_component_id UUID                        NOT NULL,
    CONSTRAINT pk_program_learning_outcome_correspondence_matrix PRIMARY KEY (id)
);

CREATE TABLE quality_assurance
(
    id                                             UUID                        NOT NULL,
    created_at                                     TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at                                     TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    deleted                                        BOOLEAN                     NOT NULL DEFAULT FALSE,
    regulatory_document                            TEXT                        NOT NULL,
    education_program_review                       TEXT                        NOT NULL,
    involvement_of_students                        TEXT                        NOT NULL,
    student_self_government                        TEXT                        NOT NULL,
    involvement_of_employers                       TEXT                        NOT NULL,
    alumni_employment                              TEXT                        NOT NULL,
    quality_issues                                 TEXT                        NOT NULL,
    educational_program_improvement                TEXT                        NOT NULL,
    academic_community_members_engaging            TEXT                        NOT NULL,
    structural_units_responsibilities_distribution TEXT                        NOT NULL,
    CONSTRAINT pk_quality_assurance PRIMARY KEY (id)
);

CREATE TABLE self_assessment_educational_program_restricted_info
(
    id                           UUID                        NOT NULL,
    created_at                   TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at                   TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    deleted                      BOOLEAN                     NOT NULL DEFAULT FALSE,
    info_description             TEXT                        NOT NULL,
    info_access_restriction_type TEXT                        NOT NULL,
    restricted_info_description  TEXT                        NOT NULL,
    restricting_access_grounds   TEXT                        NOT NULL,
    CONSTRAINT pk_self_assessment_educational_program_restricted_info PRIMARY KEY (id)
);

CREATE TABLE separate_structural_unit
(
    id                            UUID                        NOT NULL,
    created_at                    TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at                    TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    deleted                       BOOLEAN                     NOT NULL DEFAULT FALSE,
    ssu_id                        BIGINT                      NOT NULL,
    separate_structural_unit_name VARCHAR(250)                NOT NULL,
    ssu_code                      BIGINT                      NOT NULL,
    website                       VARCHAR(200)                NOT NULL,
    head_full_name_id             UUID                        NOT NULL,
    CONSTRAINT pk_separate_structural_unit PRIMARY KEY (id)
);

CREATE TABLE socialaccount_socialaccount
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    provider    VARCHAR(30)                              NOT NULL,
    uid         VARCHAR(191)                             NOT NULL,
    last_login  TIMESTAMP with time zone                 NOT NULL,
    date_joined TIMESTAMP with time zone                 NOT NULL,
    extra_data  TEXT                                     NOT NULL,
    user_id     BIGINT                                   NOT NULL,
    CONSTRAINT pk_socialaccount_socialaccount PRIMARY KEY (id)
);

CREATE TABLE specialty
(
    id             UUID                        NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    deleted        BOOLEAN                     NOT NULL DEFAULT FALSE,
    specialty_code INTEGER                     NOT NULL,
    specialty      VARCHAR(250)                NOT NULL,
    CONSTRAINT pk_specialty PRIMARY KEY (id)
);

CREATE TABLE structural_subdivision
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    responsible_department VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_structural_subdivision PRIMARY KEY (id)
);

CREATE TABLE student
(
    id              UUID                        NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    deleted         BOOLEAN                     NOT NULL DEFAULT FALSE,
    birthdate       TIMESTAMP WITHOUT TIME ZONE,
    phone_number    VARCHAR(15)                 NOT NULL,
    address         VARCHAR(255)                NOT NULL,
    student_id      VARCHAR(15)                 NOT NULL,
    enrollment_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    student_type    VARCHAR(255)                NOT NULL,
    user_id         UUID                        NOT NULL,
    CONSTRAINT pk_student PRIMARY KEY (id)
);

CREATE TABLE subdivision
(
    id                     UUID                        NOT NULL,
    created_at             TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at             TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    deleted                BOOLEAN                     NOT NULL DEFAULT FALSE,
    responsible_department VARCHAR(255)                NOT NULL,
    CONSTRAINT pk_subdivision PRIMARY KEY (id)
);

CREATE TABLE table_annex
(
    id         UUID                        NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    deleted    BOOLEAN                     NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_table_annex PRIMARY KEY (id)
);

CREATE TABLE table_annex_program_educational_components_informations
(
    program_educational_components_informations_id UUID NOT NULL,
    table_annex_id                                 UUID NOT NULL,
    CONSTRAINT pk_table_annex_programeducationalcomponentsinformations PRIMARY KEY (program_educational_components_informations_id, table_annex_id)
);

CREATE TABLE table_annex_program_learning_outcome_correspondence_matrixes
(
    id                                            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tablesannex_id                                BIGINT                                  NOT NULL,
    programlearningoutcomecorrespondencematrix_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_table_annex_program_learning_outcome_correspondence_matrix PRIMARY KEY (id)
);

CREATE TABLE table_annex_teacher_summary_informations
(
    table_annex_id                  UUID NOT NULL,
    teacher_summary_informations_id UUID NOT NULL,
    CONSTRAINT pk_table_annex_teachersummaryinformations PRIMARY KEY (table_annex_id, teacher_summary_informations_id)
);

CREATE TABLE teacher
(
    id           UUID                        NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    deleted      BOOLEAN                     NOT NULL DEFAULT FALSE,
    birthdate    TIMESTAMP WITHOUT TIME ZONE,
    phone_number VARCHAR(15)                 NOT NULL,
    address      VARCHAR(255)                NOT NULL,
    teacher_id   VARCHAR(15)                 NOT NULL,
    hire_date    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    user_id      UUID                        NOT NULL,
    CONSTRAINT pk_teacher PRIMARY KEY (id)
);

CREATE TABLE teacher_department
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    teacher_id                BIGINT                                  NOT NULL,
    structural_subdivision_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_teacher_department PRIMARY KEY (id)
);

CREATE TABLE teacher_summary_information
(
    id                    UUID                        NOT NULL,
    created_at            TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at            TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    deleted               BOOLEAN                     NOT NULL DEFAULT FALSE,
    teacher_qualification TEXT                        NOT NULL,
    teacher_experience    INTEGER                     NOT NULL,
    rationale             TEXT                        NOT NULL,
    subdivision_id        UUID                        NOT NULL,
    teacher_full_name_id  UUID                        NOT NULL,
    CONSTRAINT pk_teacher_summary_information PRIMARY KEY (id)
);

CREATE TABLE teacher_summary_information_educational_components_informations
(
    program_educational_components_informations_id UUID NOT NULL,
    teacher_summary_information_id                 UUID NOT NULL,
    CONSTRAINT pk_teachersummaryinformationeducationalcomponentsinformations PRIMARY KEY (program_educational_components_informations_id,
                                                                                          teacher_summary_information_id)
);

CREATE TABLE public."user"
(
    id           UUID                        NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    deleted      BOOLEAN                     NOT NULL DEFAULT FALSE,
    password     VARCHAR(128)                NOT NULL,
    last_login   TIMESTAMP WITHOUT TIME ZONE,
    is_superuser BOOLEAN                     NOT NULL,
    username     VARCHAR(150)                NOT NULL,
    email        VARCHAR(254)                NOT NULL,
    is_staff     BOOLEAN                     NOT NULL,
    is_active    BOOLEAN                     NOT NULL,
    name         VARCHAR(255)                NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE user_groups
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id  BIGINT                                  NOT NULL,
    group_id INTEGER                                 NOT NULL,
    CONSTRAINT pk_user_groups PRIMARY KEY (id)
);

CREATE TABLE user_permissions
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id       BIGINT                                  NOT NULL,
    permission_id INTEGER                                 NOT NULL,
    CONSTRAINT pk_user_permissions PRIMARY KEY (id)
);

CREATE UNIQUE INDEX Teacher_department_teacher_id_structuralsub_6e690524_uniq ON teacher_department (teacher_id, structural_subdivision_id);

CREATE INDEX Teacher_teacher_id_d3af3ce2_like ON teacher (teacher_id);

CREATE INDEX auth_group_name_a6ea08ec_like ON auth_group (name);

CREATE UNIQUE INDEX auth_group_permissions_group_id_permission_id_0cd325b0_uniq ON auth_group_permissions (group_id, permission_id);

CREATE UNIQUE INDEX auth_permission_codename_01ab375a_uniq ON auth_permission (codename);

CREATE UNIQUE INDEX education_program_accred_educationprogramaccredit_03820633_uniq ON education_program_accreditation_information_language_of (education_program_accreditation_information_id, language_id);

CREATE UNIQUE INDEX education_program_accred_educationprogramaccredit_e5fec51d_uniq ON education_program_accreditation_information_other_education (education_program_accreditation_information_id,
                                                                                                                                                    structural_subdivision_id);

CREATE UNIQUE INDEX other_higher_education_p_otherhighereducationprog_59a91c0e_uniq ON other_higher_education_program_education_program (otherhighereducationprogram_id, educationprogram_id);

CREATE UNIQUE INDEX socialaccount_socialaccount_provider_uid_fc810c6e_uniq ON socialaccount_socialaccount (provider, uid);

CREATE INDEX student_student_id_53c349bf_like ON student (student_id);

CREATE UNIQUE INDEX table_annex_program_lear_tablesannex_id_programle_33701012_uniq ON table_annex_program_learning_outcome_correspondence_matrix (tablesannex_id, programlearningoutcomecorrespondencematrix_id);

CREATE UNIQUE INDEX user_groups_user_id_group_id_b88eab82_uniq ON user_groups (user_id, group_id);

CREATE UNIQUE INDEX user_permissions_user_id_permission_id_43338c45_uniq ON user_permissions (user_id, permission_id);

CREATE INDEX user_username_06e46fe6_like ON "user" (username);

ALTER TABLE authtoken_token
    ADD CONSTRAINT FK_AUTHTOKEN_TOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

CREATE UNIQUE INDEX authtoken_token_user_id_key ON authtoken_token (user_id);

ALTER TABLE auth_group_permissions
    ADD CONSTRAINT FK_AUTH_GROUP_PERMISSIONS_ON_GROUP FOREIGN KEY (group_id) REFERENCES auth_group (id);

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON auth_group_permissions (group_id);

ALTER TABLE auth_group_permissions
    ADD CONSTRAINT FK_AUTH_GROUP_PERMISSIONS_ON_PERMISSION FOREIGN KEY (permission_id) REFERENCES auth_permission (id);

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON auth_group_permissions (permission_id);

ALTER TABLE education_program_accreditation_information_language_of
    ADD CONSTRAINT FK_EDUCATIONPROGRAMACCREDITATIONINFORMATIONLANGUAGE_ON_LANGUAGE FOREIGN KEY (language_id) REFERENCES language (id);

CREATE INDEX education_program_accredit_language_id_07a75e84 ON education_program_accreditation_information_language_of (language_id);

ALTER TABLE education_program_accreditation_information
    ADD CONSTRAINT FK_EDUCATIONPROGRAMACCREDITATIONINFORMATION_ON_EDUCATIONPROGRAM FOREIGN KEY (education_program_id) REFERENCES education_program (id);

CREATE INDEX education_program_accredit_education_program_id_c213effa ON education_program_accreditation_information (education_program_id);

ALTER TABLE education_program_accreditation_information
    ADD CONSTRAINT FK_EDUCATIONPROGRAMACCREDITATIONINFORMATION_ON_FIELDOFSTUDY FOREIGN KEY (field_of_study_id) REFERENCES field_of_study (id);

CREATE INDEX education_program_accredit_field_of_study_id_af2c4c0b ON education_program_accreditation_information (field_of_study_id);

ALTER TABLE education_program_accreditation_information
    ADD CONSTRAINT FK_EDUCATIONPROGRAMACCREDITATIONINFORMATIO_ON_GUARANTEEFULLNAME FOREIGN KEY (guarantee_full_name_id) REFERENCES teacher (id);

CREATE INDEX education_program_accredit_guarantee_full_name_id_f721fbaf ON education_program_accreditation_information (guarantee_full_name_id);

ALTER TABLE education_program_accreditation_information_other_education
    ADD CONSTRAINT FK_EDUCATIONPROGRAMACCREDITATIONINFORM_ON_STRUCTURALSUBDIVISION FOREIGN KEY (structural_subdivision_id) REFERENCES structural_subdivision (id);

CREATE INDEX education_program_accredit_structural_subdivision_id_18eebbfe ON education_program_accreditation_information (structural_subdivision_id);

CREATE INDEX education_program_accredit_structural_subdivision_id_72819120 ON education_program_accreditation_information_other_education (structural_subdivision_id);

ALTER TABLE education_program_accreditation_information_other_education
    ADD CONSTRAINT FK_EDUCATIONPROGRAMACCREDITATIO_ON_EDUCATIONPROGRAMACCRED4VrEyB FOREIGN KEY (education_program_accreditation_information_id) REFERENCES education_program_accreditation_information (id);

CREATE INDEX education_program_accredit_educationprogramaccreditat_82eea96e ON education_program_accreditation_information_other_education (education_program_accreditation_information_id);

ALTER TABLE education_program_accreditation_information_language_of
    ADD CONSTRAINT FK_EDUCATIONPROGRAMACCREDITATIO_ON_EDUCATIONPROGRAMACCREDITATIO FOREIGN KEY (education_program_accreditation_information_id) REFERENCES education_program_accreditation_information (id);

CREATE INDEX education_program_accredit_educationprogramaccreditat_77df1be5 ON education_program_accreditation_information_language_of (education_program_accreditation_information_id);

ALTER TABLE education_program_accreditation_information
    ADD CONSTRAINT FK_EDUCATION_PROGRAM_ACCREDITATION_INFORMATION_ON_SPECIALTY FOREIGN KEY (specialty_id) REFERENCES specialty (id);

CREATE INDEX education_program_accredit_specialty_id_9c56be99 ON education_program_accreditation_information (specialty_id);

ALTER TABLE education_program_accreditation_information
    ADD CONSTRAINT FK_EDUCATION_PROGRAM_ACCREDITATION_INFORMATION_ON_SUBDIVISION FOREIGN KEY (subdivision_id) REFERENCES subdivision (id);

CREATE INDEX education_program_accredit_subdivision_id_18eebbfe ON education_program_accreditation_information (subdivision_id);

ALTER TABLE education_program_document
    ADD CONSTRAINT FK_EDUCATION_PROGRAM_DOCUMENT_ON_GENERAL_INFORMATION FOREIGN KEY (general_information_id) REFERENCES general_information (id);

ALTER TABLE education_statistics
    ADD CONSTRAINT FK_EDUCATION_STATISTICS_ON_GENERAL_INFORMATION FOREIGN KEY (general_information_id) REFERENCES general_information (id);

ALTER TABLE general_information
    ADD CONSTRAINT FK_GENERALINFORMATION_ON_EDUCATIONPROGRAMACCREDITATIONINFORMATI FOREIGN KEY (education_program_accreditation_information_id) REFERENCES education_program_accreditation_information (id);

CREATE INDEX general_information_education_program_accredit_abab7da5 ON general_information (education_program_accreditation_information_id);

ALTER TABLE general_information
    ADD CONSTRAINT FK_GENERALINFORMATION_ON_HIGHEREDUCATIONINSTITUTIONINFORMATION FOREIGN KEY (higher_education_institution_information_id) REFERENCES higher_education_institution_information (id);

CREATE INDEX general_information_higher_education_instituti_8a77b1fb ON general_information (higher_education_institution_information_id);

ALTER TABLE general_information
    ADD CONSTRAINT FK_GENERALINFORMATION_ON_SELFASSESSMENTEDUCATIONALPROGRAMRESTRI FOREIGN KEY (self_assessment_educational_program_restricted_info_id) REFERENCES self_assessment_educational_program_restricted_info (id);

CREATE INDEX general_information_self_assessment_educationa_dbed7cf2 ON general_information (self_assessment_educational_program_restricted_info_id);

ALTER TABLE general_question_answer
    ADD CONSTRAINT FK_GENERALQUESTIONANSWER_ON_CONTROLMEASURESANDACADEMICINTEGRITY FOREIGN KEY (control_measures_and_academic_integrity_id) REFERENCES control_measures_and_academic_integrity (id);

CREATE INDEX general_question_answer_control_measures_and_acade_bd5cef5d ON general_question_answer (control_measures_and_academic_integrity_id);

ALTER TABLE general_question_answer
    ADD CONSTRAINT FK_GENERALQUESTIONANSWER_ON_EDUCATIONALENVIRONMENTANDMATERIALRE FOREIGN KEY (educational_environment_and_material_resources_id) REFERENCES educational_environment_and_material_resources (id);

CREATE INDEX general_question_answer_educational_environment_an_0c16cdc5 ON general_question_answer (educational_environment_and_material_resources_id);

ALTER TABLE general_question_answer
    ADD CONSTRAINT FK_GENERALQUESTIONANSWER_ON_EDUCATIONALPROGRAMDEVELOPMENTPERSPE FOREIGN KEY (educational_program_development_perspectives_id) REFERENCES op_development_perspectives (id);

CREATE INDEX general_question_answer_educational_program_develo_797ade6e ON general_question_answer (educational_program_development_perspectives_id);

ALTER TABLE general_question_answer
    ADD CONSTRAINT FK_GENERALQUESTIONANSWER_ON_EDUCATIONALPROGRAMLEARNINGANDTEACHI FOREIGN KEY (educational_program_learning_and_teaching_id) REFERENCES educational_program_learning_and_teaching (id);

CREATE INDEX general_question_answer_educational_program_learni_97f7172e ON general_question_answer (educational_program_learning_and_teaching_id);

ALTER TABLE general_question_answer
    ADD CONSTRAINT FK_GENERALQUESTIONANSWER_ON_EDUCATIONALPROGRAMSTRUCTUREANDCONTE FOREIGN KEY (educational_program_structure_and_content_id) REFERENCES general_question_answer_educational_program_structure_n_content (id);

CREATE INDEX general_question_answer_educational_program_struct_2f47bf23 ON general_question_answer (educational_program_structure_and_content_id);

ALTER TABLE general_question_answer
    ADD CONSTRAINT FK_GENERALQUESTIONANSWER_ON_EDUCATIONALTRANSPARENCYANDPUBLICITY FOREIGN KEY (educational_transparency_and_publicity_id) REFERENCES educational_transparency_and_publicity (id);

CREATE INDEX general_question_answer_educational_transparency_a_456511d4 ON general_question_answer (educational_transparency_and_publicity_id);

ALTER TABLE general_information
    ADD CONSTRAINT FK_GENERAL_INFORMATION_ON_EDUCATION_PROGRAM_GENERAL_INFORMATION FOREIGN KEY (education_program_general_information_id) REFERENCES education_program_general_information (id);

CREATE INDEX general_information_education_program_general__fdcf62e6 ON general_information (education_program_general_information_id);

ALTER TABLE general_information
    ADD CONSTRAINT FK_GENERAL_INFORMATION_ON_HEI_LINKS_IN_EDEBO FOREIGN KEY (hei_links_in_edebo_id) REFERENCES hei_links_in_edebo (id);

CREATE INDEX general_information_hei_links_in_edebo_id_86baa426 ON general_information (hei_links_in_edebo_id);

ALTER TABLE general_information
    ADD CONSTRAINT FK_GENERAL_INFORMATION_ON_HIGHER_EDUCATION_INSTITUTION_AREA FOREIGN KEY (higher_education_institution_area_id) REFERENCES higher_education_institution_area (id);

CREATE INDEX general_information_higher_education_instituti_35f8bd71 ON general_information (higher_education_institution_area_id);

ALTER TABLE general_question_answer
    ADD CONSTRAINT FK_GENERAL_QUESTION_ANSWER_ON_EDUCATIONAL_PROGRAM FOREIGN KEY (educational_program_id) REFERENCES educational_program (id);

CREATE INDEX general_question_answer_educational_program_id_c4af4251 ON general_question_answer (educational_program_id);

ALTER TABLE general_question_answer
    ADD CONSTRAINT FK_GENERAL_QUESTION_ANSWER_ON_EDUCATIONAL_PROGRAM_ACCESS FOREIGN KEY (educational_program_access_id) REFERENCES educational_program_access (id);

CREATE INDEX general_question_answer_educational_program_access_id_925b7575 ON general_question_answer (educational_program_access_id);

ALTER TABLE general_question_answer
    ADD CONSTRAINT FK_GENERAL_QUESTION_ANSWER_ON_EDUCATIONAL_PROGRAM_DESIGN FOREIGN KEY (educational_program_design_id) REFERENCES education_program_design (id);

CREATE INDEX general_question_answer_educational_program_design_id_857a65e3 ON general_question_answer (educational_program_design_id);

ALTER TABLE general_question_answer
    ADD CONSTRAINT FK_GENERAL_QUESTION_ANSWER_ON_HUMAN_RESOURCES FOREIGN KEY (human_resources_id) REFERENCES human_resources (id);

CREATE INDEX general_question_answer_human_resources_id_151f132b ON general_question_answer (human_resources_id);

ALTER TABLE general_question_answer
    ADD CONSTRAINT FK_GENERAL_QUESTION_ANSWER_ON_QUALITY_ASSURANCE FOREIGN KEY (quality_assurance_id) REFERENCES quality_assurance (id);

CREATE INDEX general_question_answer_quality_assurance_id_61cd8b08 ON general_question_answer (quality_assurance_id);

ALTER TABLE higher_educational_institution
    ADD CONSTRAINT FK_HIGHER_EDUCATIONAL_INSTITUTION_ON_HEAD_FULL_NAME FOREIGN KEY (head_full_name_id) REFERENCES teacher (id);

CREATE INDEX higher_educational_institution_head_full_name_id_308eb478 ON higher_educational_institution (head_full_name_id);

ALTER TABLE higher_education_institution_information
    ADD CONSTRAINT FK_HIGHER_EDUCATION_INSTITUTION_INFORMATION_ON_HEI FOREIGN KEY (hei_id) REFERENCES higher_educational_institution (id);

CREATE INDEX higher_education_institution_information_hei_id_b8abf83f ON higher_education_institution_information (hei_id);

ALTER TABLE higher_education_institution_information
    ADD CONSTRAINT FK_HIGHER_EDUCATION_INSTITUTION_INFORMATION_ON_SSU FOREIGN KEY (ssu_id) REFERENCES separate_structural_unit (id);

CREATE INDEX higher_education_institution_information_ssu_id_c2d84df8 ON higher_education_institution_information (ssu_id);

ALTER TABLE information_on_self_assessment_of_educational_program
    ADD CONSTRAINT FK_INFORMATIONONSELFASSESSMENTOFEDUCATIONALPROGR_ON_TABLESANNEX FOREIGN KEY (tables_annex_id) REFERENCES table_annex (id);

CREATE INDEX information_on_self_assess_tables_annex_id_1b3c1ad5 ON information_on_self_assessment_of_educational_program (tables_annex_id);

ALTER TABLE information_on_self_assessment_of_educational_program
    ADD CONSTRAINT FK_INFORMATIONONSELFASSESSMENTOFEDUCATION_ON_GENERALINFORMATION FOREIGN KEY (general_information_id) REFERENCES general_information (id);

CREATE INDEX information_on_self_assess_general_information_id_0ae85ecf ON information_on_self_assessment_of_educational_program (general_information_id);

ALTER TABLE information_on_self_assessment_of_educational_program
    ADD CONSTRAINT FK_INFORMATIONONSELFASSESSMENTOFEDUCAT_ON_GENERALQUESTIONANSWER FOREIGN KEY (general_question_answer_id) REFERENCES general_question_answer (id);

CREATE INDEX information_on_self_assess_general_question_answer_id_6feae976 ON information_on_self_assessment_of_educational_program (general_question_answer_id);

ALTER TABLE program_educational_components_information
    ADD CONSTRAINT FK_PROGRAMEDUCATIONALCOMPONENTSINFO_ON_EDUCATIONPROGRAMDOCUMENT FOREIGN KEY (education_program_document_id) REFERENCES education_program_document (id);

ALTER TABLE program_learning_outcome_correspondence_matrix
    ADD CONSTRAINT FK_PROGRAMLEARNINGOUTCOMECORRESPONDENCE_ON_EDUCATIONALCOMPONENT FOREIGN KEY (educational_component_id) REFERENCES program_educational_components_information (id);

CREATE INDEX program_learning_outcome_c_educational_component_id_0475d371 ON program_learning_outcome_correspondence_matrix (educational_component_id);

ALTER TABLE separate_structural_unit
    ADD CONSTRAINT FK_SEPARATE_STRUCTURAL_UNIT_ON_HEAD_FULL_NAME FOREIGN KEY (head_full_name_id) REFERENCES teacher (id);

CREATE INDEX separate_structural_unit_head_full_name_id_491f206d ON separate_structural_unit (head_full_name_id);

ALTER TABLE socialaccount_socialaccount
    ADD CONSTRAINT FK_SOCIALACCOUNT_SOCIALACCOUNT_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

CREATE INDEX socialaccount_socialaccount_user_id_8146e70c ON socialaccount_socialaccount (user_id);

ALTER TABLE student
    ADD CONSTRAINT FK_STUDENT_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

CREATE UNIQUE INDEX student_user_id_key ON student (user_id);

ALTER TABLE teacher
    ADD CONSTRAINT FK_TEACHER_ON_USER FOREIGN KEY (user_id) REFERENCES public."user" (id);

CREATE INDEX Teacher_department_structural_subdivision_id_7c546132 ON teacher_department (structural_subdivision_id);

ALTER TABLE teacher_department
    ADD CONSTRAINT FK_TEACHER_DEPARTMENT_ON_TEACHER FOREIGN KEY (teacher_id) REFERENCES teacher (id);

CREATE INDEX Teacher_department_teacher_id_f4d2f436 ON teacher_department (teacher_id);

ALTER TABLE teacher
    ADD CONSTRAINT FK_TEACHER_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

CREATE UNIQUE INDEX Teacher_user_id_key ON teacher (user_id);

ALTER TABLE teacher_summary_information
    ADD CONSTRAINT FK_TEACHER_SUMMARY_INFORMATION_ON_STRUCTURAL_SUBDIVISION FOREIGN KEY (structural_subdivision_id) REFERENCES structural_subdivision (id);

CREATE INDEX teacher_summary_information_structural_subdivision_id_80909189 ON teacher_summary_information (structural_subdivision_id);

ALTER TABLE teacher_summary_information
    ADD CONSTRAINT FK_TEACHER_SUMMARY_INFORMATION_ON_TEACHER_FULL_NAME FOREIGN KEY (teacher_full_name_id) REFERENCES teacher (id);

CREATE INDEX teacher_summary_information_teacher_full_name_id_6fd5f70f ON teacher_summary_information (teacher_full_name_id);

ALTER TABLE user_groups
    ADD CONSTRAINT FK_USER_GROUPS_ON_GROUP FOREIGN KEY (group_id) REFERENCES auth_group (id);

CREATE INDEX user_groups_group_id_9afc8d0e ON user_groups (group_id);

ALTER TABLE user_groups
    ADD CONSTRAINT FK_USER_GROUPS_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

CREATE INDEX user_groups_user_id_5f6f5a90 ON user_groups (user_id);

ALTER TABLE user_permissions
    ADD CONSTRAINT FK_USER_PERMISSIONS_ON_PERMISSION FOREIGN KEY (permission_id) REFERENCES auth_permission (id);

CREATE INDEX user_permissions_permission_id_0b93982e ON user_permissions (permission_id);

ALTER TABLE general_information_education_programs
    ADD CONSTRAINT fk_geninfedupro_on_education_program FOREIGN KEY (education_programs_id) REFERENCES education_program (id);

ALTER TABLE general_information_education_programs
    ADD CONSTRAINT fk_geninfedupro_on_general_information FOREIGN KEY (general_information_id) REFERENCES general_information (id);

ALTER TABLE table_annex_program_educational_components_informations
    ADD CONSTRAINT fk_tabannproeducominf_on_programeducationalcomponentsinformatio FOREIGN KEY (program_educational_components_informations_id) REFERENCES program_educational_components_information (id);

ALTER TABLE table_annex_program_educational_components_informations
    ADD CONSTRAINT fk_tabannproeducominf_on_table_annex FOREIGN KEY (table_annex_id) REFERENCES table_annex (id);

ALTER TABLE table_annex_program_learning_outcome_correspondence_matrixes
    ADD CONSTRAINT fk_tabannproleaoutcormat_on_programlearningoutcomecorrespondenc FOREIGN KEY (program_learning_outcome_correspondence_matrixes_id) REFERENCES program_learning_outcome_correspondence_matrix (id);

ALTER TABLE table_annex_program_learning_outcome_correspondence_matrixes
    ADD CONSTRAINT fk_tabannproleaoutcormat_on_table_annex FOREIGN KEY (table_annex_id) REFERENCES table_annex (id);

ALTER TABLE table_annex_teacher_summary_informations
    ADD CONSTRAINT fk_tabannteasuminf_on_table_annex FOREIGN KEY (table_annex_id) REFERENCES table_annex (id);

ALTER TABLE table_annex_teacher_summary_informations
    ADD CONSTRAINT fk_tabannteasuminf_on_teacher_summary_information FOREIGN KEY (teacher_summary_informations_id) REFERENCES teacher_summary_information (id);

ALTER TABLE teacher_subdivisions
    ADD CONSTRAINT fk_teasub_on_subdivision FOREIGN KEY (subdivisions_id) REFERENCES subdivision (id);

ALTER TABLE teacher_subdivisions
    ADD CONSTRAINT fk_teasub_on_teacher FOREIGN KEY (teacher_id) REFERENCES teacher (id);

ALTER TABLE teacher_summary_information_educational_components_informations
    ADD CONSTRAINT fk_teasuminfeducominf_on_programeducationalcomponentsinformatio FOREIGN KEY (program_educational_components_informations_id) REFERENCES program_educational_components_information (id);

ALTER TABLE teacher_summary_information_educational_components_informations
    ADD CONSTRAINT fk_teasuminfeducominf_on_teacher_summary_information FOREIGN KEY (teacher_summary_information_id) REFERENCES teacher_summary_information (id);

ALTER TABLE public.user_auth_groups
    ADD CONSTRAINT fk_useautgro_on_auth_group FOREIGN KEY (auth_groups_id) REFERENCES auth_group (id);

ALTER TABLE public.user_auth_groups
    ADD CONSTRAINT fk_useautgro_on_user FOREIGN KEY (user_id) REFERENCES public."user" (id);

ALTER TABLE public.user_auth_permissions
    ADD CONSTRAINT fk_useautper_on_auth_permission FOREIGN KEY (auth_permissions_id) REFERENCES auth_permission (id);

ALTER TABLE public.user_auth_permissions
    ADD CONSTRAINT fk_useautper_on_user FOREIGN KEY (user_id) REFERENCES public."user" (id);
