
CREATE TABLE auth_group
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(150)                             NOT NULL,
    CONSTRAINT pk_auth_group PRIMARY KEY (id)
);

CREATE TABLE auth_group_permissions
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    group_id      INTEGER                                 NOT NULL,
    permission_id INTEGER                                 NOT NULL,
    CONSTRAINT pk_auth_group_permissions PRIMARY KEY (id)
);

CREATE TABLE auth_permission
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255)                             NOT NULL,
    codename VARCHAR(100)                             NOT NULL,
    CONSTRAINT pk_auth_permission PRIMARY KEY (id)
);

CREATE TABLE authtoken_token
(
    key     VARCHAR(40)              NOT NULL,
    created TIMESTAMP with time zone NOT NULL,
    user_id BIGINT                   NOT NULL,
    CONSTRAINT pk_authtoken_token PRIMARY KEY (key)
);

CREATE TABLE control_measures_and_academic_integrity
(
    id                                                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description                                          TEXT                                    NOT NULL,
    clarity_criteria                                     TEXT                                    NOT NULL,
    information_provision                                TEXT                                    NOT NULL,
    compliance_requirements                              TEXT                                    NOT NULL,
    accessibility_certification_procedure                TEXT                                    NOT NULL,
    objectivity_procedures                               TEXT                                    NOT NULL,
    repeating_control_measures_procedures                TEXT                                    NOT NULL,
    appeal_procedure_and_results_of_control_measures     TEXT                                    NOT NULL,
    policies_and_standards_documents                     TEXT                                    NOT NULL,
    combating_violations_of_academic_integrity_solutions TEXT                                    NOT NULL,
    promoting_academic_integrity                         TEXT                                    NOT NULL,
    responding_to_violations_of_academic_integrity       TEXT                                    NOT NULL,
    CONSTRAINT pk_control_measures_and_academic_integrity PRIMARY KEY (id)
);

CREATE TABLE education_program
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    education_program_id BIGINT                                  NOT NULL,
    name                 VARCHAR(250)                            NOT NULL,
    CONSTRAINT pk_education_program PRIMARY KEY (id)
);

CREATE TABLE education_program_accreditation_information
(
    id                                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    specialty_licensing_info          VARCHAR(250)                            NOT NULL,
    cycle                             VARCHAR(250)                            NOT NULL,
    specialization                    VARCHAR(250),
    program_type                      VARCHAR(250)                            NOT NULL,
    admission_degree                  VARCHAR(250)                            NOT NULL,
    duration                          VARCHAR(255)                            NOT NULL,
    education_program_forms           VARCHAR(255)                            NOT NULL,
    location                          VARCHAR(255)                            NOT NULL,
    grants_professional_qualification INTEGER                                 NOT NULL,
    professional_qualification        VARCHAR(255),
    guarantee_id                      BIGINT                                  NOT NULL,
    guarantee_position                VARCHAR(255)                            NOT NULL,
    guarantee_email                   VARCHAR(254)                            NOT NULL,
    guarantee_phone                   VARCHAR(20)                             NOT NULL,
    additional_phone                  VARCHAR(20),
    education_program_id              BIGINT                                  NOT NULL,
    field_of_study_id                 BIGINT                                  NOT NULL,
    guarantee_full_name_id            BIGINT                                  NOT NULL,
    specialty_id                      BIGINT                                  NOT NULL,
    structural_subdivision_id         BIGINT                                  NOT NULL,
    CONSTRAINT pk_education_program_accreditation_information PRIMARY KEY (id)
);

CREATE TABLE education_program_accreditation_information_language_of
(
    id                                             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    education_program_accreditation_information_id BIGINT                                  NOT NULL,
    language_id                                    BIGINT                                  NOT NULL,
    CONSTRAINT pk_education_program_accreditation_information_language_of PRIMARY KEY (id)
);

CREATE TABLE education_program_accreditation_information_other_education
(
    id                                             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    education_program_accreditation_information_id BIGINT                                  NOT NULL,
    structural_subdivision_id                      BIGINT                                  NOT NULL,
    CONSTRAINT pk_education_program_accreditation_information_other_education PRIMARY KEY (id)
);

CREATE TABLE education_program_design
(
    id                                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    goals                                    TEXT                                    NOT NULL,
    uniqueness                               TEXT                                    NOT NULL,
    stakeholder_student                      TEXT                                    NOT NULL,
    stakeholder_employer                     TEXT                                    NOT NULL,
    stakeholder_academic                     TEXT                                    NOT NULL,
    stakeholder_other                        TEXT                                    NOT NULL,
    market_trends                            TEXT                                    NOT NULL,
    industry_and_regional_context            TEXT                                    NOT NULL,
    domestic_and_foreign_programs_experience TEXT                                    NOT NULL,
    learning_experience_achieve              TEXT                                    NOT NULL,
    national_qualifications_level            TEXT                                    NOT NULL,
    CONSTRAINT pk_education_program_design PRIMARY KEY (id)
);

CREATE TABLE education_program_document
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    education_program_doc VARCHAR(100)                            NOT NULL,
    curriculum_doc        VARCHAR(100)                            NOT NULL,
    reviews               VARCHAR(100),
    CONSTRAINT pk_education_program_document PRIMARY KEY (id)
);

CREATE TABLE education_program_general_information
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    history_and_development TEXT                                    NOT NULL,
    CONSTRAINT pk_education_program_general_information PRIMARY KEY (id)
);

CREATE TABLE education_statistics
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    study_course_year INTEGER                                 NOT NULL,
    academic_year     VARCHAR(11)                             NOT NULL,
    enrollment        INTEGER                                 NOT NULL,
    full_time         INTEGER                                 NOT NULL,
    part_time         INTEGER                                 NOT NULL,
    foreign_full_time INTEGER                                 NOT NULL,
    foreign_part_time INTEGER                                 NOT NULL,
    CONSTRAINT pk_education_statistics PRIMARY KEY (id)
);

CREATE TABLE educational_environment_and_material_resources
(
    id                                            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    financial_resources                           TEXT                                    NOT NULL,
    educational_environment                       TEXT                                    NOT NULL,
    safety_measures                               TEXT                                    NOT NULL,
    support_services                              TEXT                                    NOT NULL,
    special_needs_people_education                TEXT                                    NOT NULL,
    policy_and_procedures_for_conflict_resolution TEXT                                    NOT NULL,
    CONSTRAINT pk_educational_environment_and_material_resources PRIMARY KEY (id)
);

CREATE TABLE educational_program
(
    id                                          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description                                 TEXT                                    NOT NULL,
    research_preparation                        TEXT                                    NOT NULL,
    teaching_preparation                        TEXT                                    NOT NULL,
    supervisor_relevance                        TEXT                                    NOT NULL,
    research_support                            TEXT                                    NOT NULL,
    international_participation                 TEXT                                    NOT NULL,
    research_projects_supervisors_participation TEXT                                    NOT NULL,
    academic_integrity_practices                TEXT                                    NOT NULL,
    academic_integrity_preventing_violations    TEXT                                    NOT NULL,
    CONSTRAINT pk_educational_program PRIMARY KEY (id)
);

CREATE TABLE educational_program_access
(
    id                                             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    admission_rules_link                           VARCHAR(200)                            NOT NULL,
    admission_requirements                         TEXT                                    NOT NULL,
    recognition_of_education_results_accessibility TEXT                                    NOT NULL,
    admission_requirements_applying_rules_practice TEXT                                    NOT NULL,
    recognition_of_education_results_doc           TEXT                                    NOT NULL,
    education_results_doc_applying_rules_practice  TEXT                                    NOT NULL,
    CONSTRAINT pk_educational_program_access PRIMARY KEY (id)
);

CREATE TABLE educational_program_learning_and_teaching
(
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    learning_and_teaching_methods TEXT                                    NOT NULL,
    student_centered_approach     TEXT                                    NOT NULL,
    academic_freedom              TEXT                                    NOT NULL,
    learning_outcomes             TEXT                                    NOT NULL,
    learning_and_research         TEXT                                    NOT NULL,
    curriculum_update             TEXT                                    NOT NULL,
    internationalization          TEXT                                    NOT NULL,
    CONSTRAINT pk_educational_program_learning_and_teaching PRIMARY KEY (id)
);

CREATE TABLE educational_transparency_and_publicity
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    regulatory_documents      VARCHAR(1500)                           NOT NULL,
    stakeholder_feedback_link VARCHAR(200)                            NOT NULL,
    educational_program_link  VARCHAR(200)                            NOT NULL,
    CONSTRAINT pk_educational_transparency_and_publicity PRIMARY KEY (id)
);

CREATE TABLE field_of_study
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    field_of_study_code INTEGER                                 NOT NULL,
    field_of_study      VARCHAR(250)                            NOT NULL,
    CONSTRAINT pk_field_of_study PRIMARY KEY (id)
);

CREATE TABLE general_information
(
    id                                                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    education_program_accreditation_information_id         BIGINT                                  NOT NULL,
    education_program_document_id                          BIGINT                                  NOT NULL,
    education_program_general_information_id               BIGINT                                  NOT NULL,
    education_statistics_id                                BIGINT                                  NOT NULL,
    hei_links_in_edebo_id                                  BIGINT                                  NOT NULL,
    higher_education_institution_area_id                   BIGINT                                  NOT NULL,
    higher_education_institution_information_id            BIGINT                                  NOT NULL,
    other_higher_education_program_id                      BIGINT                                  NOT NULL,
    self_assessment_educational_program_restricted_info_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_general_information PRIMARY KEY (id)
);

CREATE TABLE general_question_answer
(
    id                                                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    control_measures_and_academic_integrity_id        BIGINT                                  NOT NULL,
    educational_environment_and_material_resources_id BIGINT                                  NOT NULL,
    educational_program_id                            BIGINT                                  NOT NULL,
    educational_program_access_id                     BIGINT                                  NOT NULL,
    educational_program_design_id                     BIGINT                                  NOT NULL,
    educational_program_development_perspectives_id   BIGINT                                  NOT NULL,
    educational_program_learning_and_teaching_id      BIGINT                                  NOT NULL,
    educational_program_structure_and_content_id      BIGINT                                  NOT NULL,
    educational_transparency_and_publicity_id         BIGINT                                  NOT NULL,
    human_resources_id                                BIGINT                                  NOT NULL,
    quality_assurance_id                              BIGINT                                  NOT NULL,
    CONSTRAINT pk_general_question_answer PRIMARY KEY (id)
);

CREATE TABLE general_question_answer_educational_program_structure_n_content
(
    id                                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ep_credits_amount                     INTEGER                                 NOT NULL,
    components_credits_amount             SMALLINT                                NOT NULL,
    student_electives_credits_amount      SMALLINT                                NOT NULL,
    content_compliance                    TEXT                                    NOT NULL,
    individual_learning_path              TEXT                                    NOT NULL,
    student_choice_right                  TEXT                                    NOT NULL,
    student_practical_training            TEXT                                    NOT NULL,
    student_soft_skills                   TEXT                                    NOT NULL,
    relevant_professional_standard        TEXT                                    NOT NULL,
    components_scope_correlating_approach TEXT                                    NOT NULL,
    dual_form_education_structure         TEXT                                    NOT NULL,
    CONSTRAINT pk_generalquestionanswereducationalprogramstructurencontent PRIMARY KEY (id)
);

CREATE TABLE hei_links_in_edebo
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    website VARCHAR(200)                            NOT NULL,
    CONSTRAINT pk_hei_links_in_edebo PRIMARY KEY (id)
);

CREATE TABLE higher_education_institution_area
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    area_type          VARCHAR(2)                              NOT NULL,
    all_rooms          BIGINT                                  NOT NULL,
    own_rooms          BIGINT                                  NOT NULL,
    other_rights_rooms BIGINT                                  NOT NULL,
    rented_rooms       BIGINT                                  NOT NULL,
    CONSTRAINT pk_higher_education_institution_area PRIMARY KEY (id)
);

CREATE TABLE higher_education_institution_information
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    hei_id BIGINT                                  NOT NULL,
    ssu_id BIGINT,
    CONSTRAINT pk_higher_education_institution_information PRIMARY KEY (id)
);

CREATE TABLE higher_educational_institution
(
    id                                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    hei_id                              BIGINT                                  NOT NULL,
    higher_educational_institution_name VARCHAR(250)                            NOT NULL,
    institution_code                    BIGINT                                  NOT NULL,
    website                             VARCHAR(200)                            NOT NULL,
    head_full_name_id                   BIGINT                                  NOT NULL,
    CONSTRAINT pk_higher_educational_institution PRIMARY KEY (id)
);

CREATE TABLE human_resources
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    competency_level     TEXT                                    NOT NULL,
    employers_engagement TEXT                                    NOT NULL,
    expert_involvement   TEXT                                    NOT NULL,
    teacher_development  TEXT                                    NOT NULL,
    teaching_excellence  TEXT                                    NOT NULL,
    CONSTRAINT pk_human_resources PRIMARY KEY (id)
);

CREATE TABLE information_on_self_assessment_of_educational_program
(
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    general_information_id     BIGINT                                  NOT NULL,
    general_question_answer_id BIGINT                                  NOT NULL,
    tables_annex_id            BIGINT                                  NOT NULL,
    CONSTRAINT pk_information_on_self_assessment_of_educational_program PRIMARY KEY (id)
);

CREATE TABLE language
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(50)                             NOT NULL,
    short_name VARCHAR(250)                            NOT NULL,
    CONSTRAINT pk_language PRIMARY KEY (id)
);

CREATE TABLE op_development_perspectives
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    strong_weak_points TEXT                                    NOT NULL,
    future_development TEXT                                    NOT NULL,
    CONSTRAINT pk_op_development_perspectives PRIMARY KEY (id)
);

CREATE TABLE other_higher_education_program
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    level VARCHAR(20)                             NOT NULL,
    CONSTRAINT pk_other_higher_education_program PRIMARY KEY (id)
);

CREATE TABLE other_higher_education_program_education_program
(
    id                             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    otherhighereducationprogram_id BIGINT                                  NOT NULL,
    educationprogram_id            BIGINT                                  NOT NULL,
    CONSTRAINT pk_other_higher_education_program_education_program PRIMARY KEY (id)
);

CREATE TABLE program_educational_components_information
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    component_name         VARCHAR(255)                            NOT NULL,
    component_type         VARCHAR(255)                            NOT NULL,
    syllabus               VARCHAR(255),
    special_equipment_info TEXT                                    NOT NULL,
    CONSTRAINT pk_program_educational_components_information PRIMARY KEY (id)
);

CREATE TABLE program_learning_outcome_correspondence_matrix
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                     TEXT                                    NOT NULL,
    teaching_method          VARCHAR(1000)                           NOT NULL,
    assessment_form          VARCHAR(200)                            NOT NULL,
    educational_component_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_program_learning_outcome_correspondence_matrix PRIMARY KEY (id)
);

CREATE TABLE quality_assurance
(
    id                                             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    regulatory_document                            TEXT                                    NOT NULL,
    education_program_review                       TEXT                                    NOT NULL,
    involvement_of_students                        TEXT                                    NOT NULL,
    student_self_government                        TEXT                                    NOT NULL,
    involvement_of_employers                       TEXT                                    NOT NULL,
    alumni_employment                              TEXT                                    NOT NULL,
    quality_issues                                 TEXT                                    NOT NULL,
    educational_program_improvement                TEXT                                    NOT NULL,
    academic_community_members_engaging            TEXT                                    NOT NULL,
    structural_units_responsibilities_distribution TEXT                                    NOT NULL,
    CONSTRAINT pk_quality_assurance PRIMARY KEY (id)
);

CREATE TABLE self_assessment_educational_program_restricted_info
(
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    info_description             TEXT                                    NOT NULL,
    info_access_restriction_type TEXT                                    NOT NULL,
    restricted_info_description  TEXT                                    NOT NULL,
    restricting_access_grounds   TEXT                                    NOT NULL,
    CONSTRAINT pk_self_assessment_educational_program_restricted_info PRIMARY KEY (id)
);

CREATE TABLE separate_structural_unit
(
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ssu_id                        BIGINT                                  NOT NULL,
    separate_structural_unit_name VARCHAR(250)                            NOT NULL,
    ssu_code                      BIGINT                                  NOT NULL,
    website                       VARCHAR(200)                            NOT NULL,
    head_full_name_id             BIGINT                                  NOT NULL,
    CONSTRAINT pk_separate_structural_unit PRIMARY KEY (id)
);

CREATE TABLE socialaccount_socialaccount
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    provider    VARCHAR(30)                              NOT NULL,
    uid         VARCHAR(191)                             NOT NULL,
    last_login  TIMESTAMP with time zone                 NOT NULL,
    date_joined TIMESTAMP with time zone                 NOT NULL,
    extra_data  TEXT                                     NOT NULL,
    user_id     BIGINT                                   NOT NULL,
    CONSTRAINT pk_socialaccount_socialaccount PRIMARY KEY (id)
);

CREATE TABLE specialty
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    specialty_code INTEGER                                 NOT NULL,
    specialty      VARCHAR(250)                            NOT NULL,
    CONSTRAINT pk_specialty PRIMARY KEY (id)
);

CREATE TABLE structural_subdivision
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    responsible_department VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_structural_subdivision PRIMARY KEY (id)
);

CREATE TABLE student
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    birthdate       date,
    phone_number    VARCHAR(15)                             NOT NULL,
    address         VARCHAR(255)                            NOT NULL,
    student_id      VARCHAR(15)                             NOT NULL,
    enrollment_date date                                    NOT NULL,
    student_type    INTEGER                                 NOT NULL,
    user_id         BIGINT                                  NOT NULL,
    CONSTRAINT pk_student PRIMARY KEY (id)
);

CREATE TABLE table_annex
(
    id                                            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    program_educational_components_information_id BIGINT                                  NOT NULL,
    teacher_summary_information_id                BIGINT                                  NOT NULL,
    CONSTRAINT pk_table_annex PRIMARY KEY (id)
);

CREATE TABLE table_annex_program_learning_outcome_correspondence_matrix
(
    id                                            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tablesannex_id                                BIGINT                                  NOT NULL,
    programlearningoutcomecorrespondencematrix_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_table_annex_program_learning_outcome_correspondence_matrix PRIMARY KEY (id)
);

CREATE TABLE teacher
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    birthdate    date,
    phone_number VARCHAR(15)                             NOT NULL,
    address      VARCHAR(255)                            NOT NULL,
    teacher_id   VARCHAR(15)                             NOT NULL,
    hire_date    date                                    NOT NULL,
    user_id      BIGINT                                  NOT NULL,
    CONSTRAINT pk_teacher PRIMARY KEY (id)
);

CREATE TABLE teacher_department
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    teacher_id                BIGINT                                  NOT NULL,
    structural_subdivision_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_teacher_department PRIMARY KEY (id)
);

CREATE TABLE teacher_summary_information
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    teacher_qualification     VARCHAR(200)                            NOT NULL,
    teacher_experience        INTEGER                                 NOT NULL,
    education_disciplines     TEXT                                    NOT NULL,
    rationale                 TEXT                                    NOT NULL,
    structural_subdivision_id BIGINT                                  NOT NULL,
    teacher_full_name_id      BIGINT                                  NOT NULL,
    CONSTRAINT pk_teacher_summary_information PRIMARY KEY (id)
);

CREATE TABLE "user"
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    password     VARCHAR(128)                            NOT NULL,
    last_login   TIMESTAMP with time zone,
    is_superuser BOOLEAN                                 NOT NULL,
    username     VARCHAR(150)                            NOT NULL,
    email        VARCHAR(254)                            NOT NULL,
    is_staff     BOOLEAN                                 NOT NULL,
    is_active    BOOLEAN                                 NOT NULL,
    date_joined  TIMESTAMP with time zone                NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE user_groups
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id  BIGINT                                  NOT NULL,
    group_id INTEGER                                 NOT NULL,
    CONSTRAINT pk_user_groups PRIMARY KEY (id)
);

CREATE TABLE user_permissions
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id       BIGINT                                  NOT NULL,
    permission_id INTEGER                                 NOT NULL,
    CONSTRAINT pk_user_permissions PRIMARY KEY (id)
);

CREATE UNIQUE INDEX Teacher_department_teacher_id_structuralsub_6e690524_uniq ON teacher_department (teacher_id, structural_subdivision_id);

CREATE INDEX Teacher_teacher_id_d3af3ce2_like ON teacher (teacher_id);

CREATE INDEX auth_group_name_a6ea08ec_like ON auth_group (name);

CREATE UNIQUE INDEX auth_group_permissions_group_id_permission_id_0cd325b0_uniq ON auth_group_permissions (group_id, permission_id);

CREATE UNIQUE INDEX auth_permission_codename_01ab375a_uniq ON auth_permission (codename);

CREATE UNIQUE INDEX education_program_accred_educationprogramaccredit_03820633_uniq ON education_program_accreditation_information_language_of (education_program_accreditation_information_id, language_id);

CREATE UNIQUE INDEX education_program_accred_educationprogramaccredit_e5fec51d_uniq ON education_program_accreditation_information_other_education (education_program_accreditation_information_id,
                                                                                                                                                    structural_subdivision_id);

CREATE UNIQUE INDEX other_higher_education_p_otherhighereducationprog_59a91c0e_uniq ON other_higher_education_program_education_program (otherhighereducationprogram_id, educationprogram_id);

CREATE UNIQUE INDEX socialaccount_socialaccount_provider_uid_fc810c6e_uniq ON socialaccount_socialaccount (provider, uid);

CREATE INDEX student_student_id_53c349bf_like ON student (student_id);

CREATE UNIQUE INDEX table_annex_program_lear_tablesannex_id_programle_33701012_uniq ON table_annex_program_learning_outcome_correspondence_matrix (tablesannex_id, programlearningoutcomecorrespondencematrix_id);

CREATE UNIQUE INDEX user_groups_user_id_group_id_b88eab82_uniq ON user_groups (user_id, group_id);

CREATE UNIQUE INDEX user_permissions_user_id_permission_id_43338c45_uniq ON user_permissions (user_id, permission_id);

CREATE INDEX user_username_06e46fe6_like ON "user" (username);

ALTER TABLE authtoken_token
    ADD CONSTRAINT FK_AUTHTOKEN_TOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

CREATE UNIQUE INDEX authtoken_token_user_id_key ON authtoken_token (user_id);

ALTER TABLE auth_group_permissions
    ADD CONSTRAINT FK_AUTH_GROUP_PERMISSIONS_ON_GROUP FOREIGN KEY (group_id) REFERENCES auth_group (id);

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON auth_group_permissions (group_id);

ALTER TABLE auth_group_permissions
    ADD CONSTRAINT FK_AUTH_GROUP_PERMISSIONS_ON_PERMISSION FOREIGN KEY (permission_id) REFERENCES auth_permission (id);

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON auth_group_permissions (permission_id);

ALTER TABLE education_program_accreditation_information_language_of
    ADD CONSTRAINT FK_EDUCATIONPROGRAMACCREDITATIONINFORMATIONLANGUAGE_ON_LANGUAGE FOREIGN KEY (language_id) REFERENCES language (id);

CREATE INDEX education_program_accredit_language_id_07a75e84 ON education_program_accreditation_information_language_of (language_id);

ALTER TABLE education_program_accreditation_information
    ADD CONSTRAINT FK_EDUCATIONPROGRAMACCREDITATIONINFORMATION_ON_EDUCATIONPROGRAM FOREIGN KEY (education_program_id) REFERENCES education_program (id);

CREATE INDEX education_program_accredit_education_program_id_c213effa ON education_program_accreditation_information (education_program_id);

ALTER TABLE education_program_accreditation_information
    ADD CONSTRAINT FK_EDUCATIONPROGRAMACCREDITATIONINFORMATION_ON_FIELDOFSTUDY FOREIGN KEY (field_of_study_id) REFERENCES field_of_study (id);

CREATE INDEX education_program_accredit_field_of_study_id_af2c4c0b ON education_program_accreditation_information (field_of_study_id);

ALTER TABLE education_program_accreditation_information
    ADD CONSTRAINT FK_EDUCATIONPROGRAMACCREDITATIONINFORMATIO_ON_GUARANTEEFULLNAME FOREIGN KEY (guarantee_full_name_id) REFERENCES teacher (id);

CREATE INDEX education_program_accredit_guarantee_full_name_id_f721fbaf ON education_program_accreditation_information (guarantee_full_name_id);

ALTER TABLE education_program_accreditation_information_other_education
    ADD CONSTRAINT FK_EDUCATIONPROGRAMACCREDITATIONINFORM_ON_STRUCTURALSUBDIVISION FOREIGN KEY (structural_subdivision_id) REFERENCES structural_subdivision (id);

CREATE INDEX education_program_accredit_structural_subdivision_id_18eebbfe ON education_program_accreditation_information (structural_subdivision_id);

CREATE INDEX education_program_accredit_structural_subdivision_id_72819120 ON education_program_accreditation_information_other_education (structural_subdivision_id);

ALTER TABLE education_program_accreditation_information_other_education
    ADD CONSTRAINT FK_EDUCATIONPROGRAMACCREDITATIO_ON_EDUCATIONPROGRAMACCRED4VrEyB FOREIGN KEY (education_program_accreditation_information_id) REFERENCES education_program_accreditation_information (id);

CREATE INDEX education_program_accredit_educationprogramaccreditat_82eea96e ON education_program_accreditation_information_other_education (education_program_accreditation_information_id);

ALTER TABLE education_program_accreditation_information_language_of
    ADD CONSTRAINT FK_EDUCATIONPROGRAMACCREDITATIO_ON_EDUCATIONPROGRAMACCREDITATIO FOREIGN KEY (education_program_accreditation_information_id) REFERENCES education_program_accreditation_information (id);

CREATE INDEX education_program_accredit_educationprogramaccreditat_77df1be5 ON education_program_accreditation_information_language_of (education_program_accreditation_information_id);

ALTER TABLE education_program_accreditation_information
    ADD CONSTRAINT FK_EDUCATION_PROGRAM_ACCREDITATION_INFORMATION_ON_SPECIALTY FOREIGN KEY (specialty_id) REFERENCES specialty (id);

CREATE INDEX education_program_accredit_specialty_id_9c56be99 ON education_program_accreditation_information (specialty_id);

ALTER TABLE general_information
    ADD CONSTRAINT FK_GENERALINFORMATION_ON_EDUCATIONPROGRAMACCREDITATIONINFORMATI FOREIGN KEY (education_program_accreditation_information_id) REFERENCES education_program_accreditation_information (id);

CREATE INDEX general_information_education_program_accredit_abab7da5 ON general_information (education_program_accreditation_information_id);

ALTER TABLE general_information
    ADD CONSTRAINT FK_GENERALINFORMATION_ON_HIGHEREDUCATIONINSTITUTIONINFORMATION FOREIGN KEY (higher_education_institution_information_id) REFERENCES higher_education_institution_information (id);

CREATE INDEX general_information_higher_education_instituti_8a77b1fb ON general_information (higher_education_institution_information_id);

ALTER TABLE general_information
    ADD CONSTRAINT FK_GENERALINFORMATION_ON_SELFASSESSMENTEDUCATIONALPROGRAMRESTRI FOREIGN KEY (self_assessment_educational_program_restricted_info_id) REFERENCES self_assessment_educational_program_restricted_info (id);

CREATE INDEX general_information_self_assessment_educationa_dbed7cf2 ON general_information (self_assessment_educational_program_restricted_info_id);

ALTER TABLE general_question_answer
    ADD CONSTRAINT FK_GENERALQUESTIONANSWER_ON_CONTROLMEASURESANDACADEMICINTEGRITY FOREIGN KEY (control_measures_and_academic_integrity_id) REFERENCES control_measures_and_academic_integrity (id);

CREATE INDEX general_question_answer_control_measures_and_acade_bd5cef5d ON general_question_answer (control_measures_and_academic_integrity_id);

ALTER TABLE general_question_answer
    ADD CONSTRAINT FK_GENERALQUESTIONANSWER_ON_EDUCATIONALENVIRONMENTANDMATERIALRE FOREIGN KEY (educational_environment_and_material_resources_id) REFERENCES educational_environment_and_material_resources (id);

CREATE INDEX general_question_answer_educational_environment_an_0c16cdc5 ON general_question_answer (educational_environment_and_material_resources_id);

ALTER TABLE general_question_answer
    ADD CONSTRAINT FK_GENERALQUESTIONANSWER_ON_EDUCATIONALPROGRAMDEVELOPMENTPERSPE FOREIGN KEY (educational_program_development_perspectives_id) REFERENCES op_development_perspectives (id);

CREATE INDEX general_question_answer_educational_program_develo_797ade6e ON general_question_answer (educational_program_development_perspectives_id);

ALTER TABLE general_question_answer
    ADD CONSTRAINT FK_GENERALQUESTIONANSWER_ON_EDUCATIONALPROGRAMLEARNINGANDTEACHI FOREIGN KEY (educational_program_learning_and_teaching_id) REFERENCES educational_program_learning_and_teaching (id);

CREATE INDEX general_question_answer_educational_program_learni_97f7172e ON general_question_answer (educational_program_learning_and_teaching_id);

ALTER TABLE general_question_answer
    ADD CONSTRAINT FK_GENERALQUESTIONANSWER_ON_EDUCATIONALPROGRAMSTRUCTUREANDCONTE FOREIGN KEY (educational_program_structure_and_content_id) REFERENCES general_question_answer_educational_program_structure_n_content (id);

CREATE INDEX general_question_answer_educational_program_struct_2f47bf23 ON general_question_answer (educational_program_structure_and_content_id);

ALTER TABLE general_question_answer
    ADD CONSTRAINT FK_GENERALQUESTIONANSWER_ON_EDUCATIONALTRANSPARENCYANDPUBLICITY FOREIGN KEY (educational_transparency_and_publicity_id) REFERENCES educational_transparency_and_publicity (id);

CREATE INDEX general_question_answer_educational_transparency_a_456511d4 ON general_question_answer (educational_transparency_and_publicity_id);

ALTER TABLE general_information
    ADD CONSTRAINT FK_GENERAL_INFORMATION_ON_EDUCATION_PROGRAM_DOCUMENT FOREIGN KEY (education_program_document_id) REFERENCES education_program_document (id);

CREATE INDEX general_information_education_program_document_id_154f8daa ON general_information (education_program_document_id);

ALTER TABLE general_information
    ADD CONSTRAINT FK_GENERAL_INFORMATION_ON_EDUCATION_PROGRAM_GENERAL_INFORMATION FOREIGN KEY (education_program_general_information_id) REFERENCES education_program_general_information (id);

CREATE INDEX general_information_education_program_general__fdcf62e6 ON general_information (education_program_general_information_id);

ALTER TABLE general_information
    ADD CONSTRAINT FK_GENERAL_INFORMATION_ON_EDUCATION_STATISTICS FOREIGN KEY (education_statistics_id) REFERENCES education_statistics (id);

CREATE INDEX general_information_education_statistics_id_355f9606 ON general_information (education_statistics_id);

ALTER TABLE general_information
    ADD CONSTRAINT FK_GENERAL_INFORMATION_ON_HEI_LINKS_IN_EDEBO FOREIGN KEY (hei_links_in_edebo_id) REFERENCES hei_links_in_edebo (id);

CREATE INDEX general_information_hei_links_in_edebo_id_86baa426 ON general_information (hei_links_in_edebo_id);

ALTER TABLE general_information
    ADD CONSTRAINT FK_GENERAL_INFORMATION_ON_HIGHER_EDUCATION_INSTITUTION_AREA FOREIGN KEY (higher_education_institution_area_id) REFERENCES higher_education_institution_area (id);

CREATE INDEX general_information_higher_education_instituti_35f8bd71 ON general_information (higher_education_institution_area_id);

ALTER TABLE general_information
    ADD CONSTRAINT FK_GENERAL_INFORMATION_ON_OTHER_HIGHER_EDUCATION_PROGRAM FOREIGN KEY (other_higher_education_program_id) REFERENCES other_higher_education_program (id);

CREATE INDEX general_information_other_higher_education_program_id_3d97e981 ON general_information (other_higher_education_program_id);

ALTER TABLE general_question_answer
    ADD CONSTRAINT FK_GENERAL_QUESTION_ANSWER_ON_EDUCATIONAL_PROGRAM FOREIGN KEY (educational_program_id) REFERENCES educational_program (id);

CREATE INDEX general_question_answer_educational_program_id_c4af4251 ON general_question_answer (educational_program_id);

ALTER TABLE general_question_answer
    ADD CONSTRAINT FK_GENERAL_QUESTION_ANSWER_ON_EDUCATIONAL_PROGRAM_ACCESS FOREIGN KEY (educational_program_access_id) REFERENCES educational_program_access (id);

CREATE INDEX general_question_answer_educational_program_access_id_925b7575 ON general_question_answer (educational_program_access_id);

ALTER TABLE general_question_answer
    ADD CONSTRAINT FK_GENERAL_QUESTION_ANSWER_ON_EDUCATIONAL_PROGRAM_DESIGN FOREIGN KEY (educational_program_design_id) REFERENCES education_program_design (id);

CREATE INDEX general_question_answer_educational_program_design_id_857a65e3 ON general_question_answer (educational_program_design_id);

ALTER TABLE general_question_answer
    ADD CONSTRAINT FK_GENERAL_QUESTION_ANSWER_ON_HUMAN_RESOURCES FOREIGN KEY (human_resources_id) REFERENCES human_resources (id);

CREATE INDEX general_question_answer_human_resources_id_151f132b ON general_question_answer (human_resources_id);

ALTER TABLE general_question_answer
    ADD CONSTRAINT FK_GENERAL_QUESTION_ANSWER_ON_QUALITY_ASSURANCE FOREIGN KEY (quality_assurance_id) REFERENCES quality_assurance (id);

CREATE INDEX general_question_answer_quality_assurance_id_61cd8b08 ON general_question_answer (quality_assurance_id);

ALTER TABLE higher_educational_institution
    ADD CONSTRAINT FK_HIGHER_EDUCATIONAL_INSTITUTION_ON_HEAD_FULL_NAME FOREIGN KEY (head_full_name_id) REFERENCES teacher (id);

CREATE INDEX higher_educational_institution_head_full_name_id_308eb478 ON higher_educational_institution (head_full_name_id);

ALTER TABLE higher_education_institution_information
    ADD CONSTRAINT FK_HIGHER_EDUCATION_INSTITUTION_INFORMATION_ON_HEI FOREIGN KEY (hei_id) REFERENCES higher_educational_institution (id);

CREATE INDEX higher_education_institution_information_hei_id_b8abf83f ON higher_education_institution_information (hei_id);

ALTER TABLE higher_education_institution_information
    ADD CONSTRAINT FK_HIGHER_EDUCATION_INSTITUTION_INFORMATION_ON_SSU FOREIGN KEY (ssu_id) REFERENCES separate_structural_unit (id);

CREATE INDEX higher_education_institution_information_ssu_id_c2d84df8 ON higher_education_institution_information (ssu_id);

ALTER TABLE information_on_self_assessment_of_educational_program
    ADD CONSTRAINT FK_INFORMATIONONSELFASSESSMENTOFEDUCATIONALPROGR_ON_TABLESANNEX FOREIGN KEY (tables_annex_id) REFERENCES table_annex (id);

CREATE INDEX information_on_self_assess_tables_annex_id_1b3c1ad5 ON information_on_self_assessment_of_educational_program (tables_annex_id);

ALTER TABLE information_on_self_assessment_of_educational_program
    ADD CONSTRAINT FK_INFORMATIONONSELFASSESSMENTOFEDUCATION_ON_GENERALINFORMATION FOREIGN KEY (general_information_id) REFERENCES general_information (id);

CREATE INDEX information_on_self_assess_general_information_id_0ae85ecf ON information_on_self_assessment_of_educational_program (general_information_id);

ALTER TABLE information_on_self_assessment_of_educational_program
    ADD CONSTRAINT FK_INFORMATIONONSELFASSESSMENTOFEDUCAT_ON_GENERALQUESTIONANSWER FOREIGN KEY (general_question_answer_id) REFERENCES general_question_answer (id);

CREATE INDEX information_on_self_assess_general_question_answer_id_6feae976 ON information_on_self_assessment_of_educational_program (general_question_answer_id);

ALTER TABLE other_higher_education_program_education_program
    ADD CONSTRAINT FK_OTHERHIGHEREDUCATIONPROGRAMEDUCATIONPROG_ON_EDUCATIONPROGRAM FOREIGN KEY (educationprogram_id) REFERENCES education_program (id);

CREATE INDEX other_higher_education_pro_educationprogram_id_a4fd4b94 ON other_higher_education_program_education_program (educationprogram_id);

ALTER TABLE other_higher_education_program_education_program
    ADD CONSTRAINT FK_OTHERHIGHEREDUCATIONPROGRAMED_ON_OTHERHIGHEREDUCATIONPROGRAM FOREIGN KEY (otherhighereducationprogram_id) REFERENCES other_higher_education_program (id);

CREATE INDEX other_higher_education_pro_otherhighereducationprogra_a402e620 ON other_higher_education_program_education_program (otherhighereducationprogram_id);

ALTER TABLE program_learning_outcome_correspondence_matrix
    ADD CONSTRAINT FK_PROGRAMLEARNINGOUTCOMECORRESPONDENCE_ON_EDUCATIONALCOMPONENT FOREIGN KEY (educational_component_id) REFERENCES program_educational_components_information (id);

CREATE INDEX program_learning_outcome_c_educational_component_id_0475d371 ON program_learning_outcome_correspondence_matrix (educational_component_id);

ALTER TABLE separate_structural_unit
    ADD CONSTRAINT FK_SEPARATE_STRUCTURAL_UNIT_ON_HEAD_FULL_NAME FOREIGN KEY (head_full_name_id) REFERENCES teacher (id);

CREATE INDEX separate_structural_unit_head_full_name_id_491f206d ON separate_structural_unit (head_full_name_id);

ALTER TABLE socialaccount_socialaccount
    ADD CONSTRAINT FK_SOCIALACCOUNT_SOCIALACCOUNT_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

CREATE INDEX socialaccount_socialaccount_user_id_8146e70c ON socialaccount_socialaccount (user_id);

ALTER TABLE student
    ADD CONSTRAINT FK_STUDENT_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

CREATE UNIQUE INDEX student_user_id_key ON student (user_id);

ALTER TABLE table_annex_program_learning_outcome_correspondence_matrix
    ADD CONSTRAINT FK_TABLEANNEXPROGRAMLEARNINGOUTCOMECORRESPONDENC_ON_TABLESANNEX FOREIGN KEY (tablesannex_id) REFERENCES table_annex (id);

CREATE INDEX table_annex_program_learni_tablesannex_id_f344b8fc ON table_annex_program_learning_outcome_correspondence_matrix (tablesannex_id);

ALTER TABLE table_annex_program_learning_outcome_correspondence_matrix
    ADD CONSTRAINT FK_TABLEANNEXPROGRAMLEARNINGOUT_ON_PROGRAMLEARNINGOUTCOMECORRES FOREIGN KEY (programlearningoutcomecorrespondencematrix_id) REFERENCES program_learning_outcome_correspondence_matrix (id);

CREATE INDEX table_annex_program_learni_programlearningoutcomecorr_b3989622 ON table_annex_program_learning_outcome_correspondence_matrix (programlearningoutcomecorrespondencematrix_id);

ALTER TABLE table_annex
    ADD CONSTRAINT FK_TABLE_ANNEX_ON_PROGRAM_EDUCATIONAL_COMPONENTS_INFORMATION FOREIGN KEY (program_educational_components_information_id) REFERENCES program_educational_components_information (id);

CREATE INDEX table_annex_program_educational_compon_b4ce18d9 ON table_annex (program_educational_components_information_id);

ALTER TABLE table_annex
    ADD CONSTRAINT FK_TABLE_ANNEX_ON_TEACHER_SUMMARY_INFORMATION FOREIGN KEY (teacher_summary_information_id) REFERENCES teacher_summary_information (id);

CREATE INDEX table_annex_teacher_summary_information_id_ab7699df ON table_annex (teacher_summary_information_id);

ALTER TABLE teacher_department
    ADD CONSTRAINT FK_TEACHER_DEPARTMENT_ON_STRUCTURAL_SUBDIVISION FOREIGN KEY (structural_subdivision_id) REFERENCES structural_subdivision (id);

CREATE INDEX Teacher_department_structural_subdivision_id_7c546132 ON teacher_department (structural_subdivision_id);

ALTER TABLE teacher_department
    ADD CONSTRAINT FK_TEACHER_DEPARTMENT_ON_TEACHER FOREIGN KEY (teacher_id) REFERENCES teacher (id);

CREATE INDEX Teacher_department_teacher_id_f4d2f436 ON teacher_department (teacher_id);

ALTER TABLE teacher
    ADD CONSTRAINT FK_TEACHER_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

CREATE UNIQUE INDEX Teacher_user_id_key ON teacher (user_id);

ALTER TABLE teacher_summary_information
    ADD CONSTRAINT FK_TEACHER_SUMMARY_INFORMATION_ON_STRUCTURAL_SUBDIVISION FOREIGN KEY (structural_subdivision_id) REFERENCES structural_subdivision (id);

CREATE INDEX teacher_summary_information_structural_subdivision_id_80909189 ON teacher_summary_information (structural_subdivision_id);

ALTER TABLE teacher_summary_information
    ADD CONSTRAINT FK_TEACHER_SUMMARY_INFORMATION_ON_TEACHER_FULL_NAME FOREIGN KEY (teacher_full_name_id) REFERENCES teacher (id);

CREATE INDEX teacher_summary_information_teacher_full_name_id_6fd5f70f ON teacher_summary_information (teacher_full_name_id);

ALTER TABLE user_groups
    ADD CONSTRAINT FK_USER_GROUPS_ON_GROUP FOREIGN KEY (group_id) REFERENCES auth_group (id);

CREATE INDEX user_groups_group_id_9afc8d0e ON user_groups (group_id);

ALTER TABLE user_groups
    ADD CONSTRAINT FK_USER_GROUPS_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

CREATE INDEX user_groups_user_id_5f6f5a90 ON user_groups (user_id);

ALTER TABLE user_permissions
    ADD CONSTRAINT FK_USER_PERMISSIONS_ON_PERMISSION FOREIGN KEY (permission_id) REFERENCES auth_permission (id);

CREATE INDEX user_permissions_permission_id_0b93982e ON user_permissions (permission_id);

ALTER TABLE user_permissions
    ADD CONSTRAINT FK_USER_PERMISSIONS_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

CREATE INDEX user_permissions_user_id_20aca447 ON user_permissions (user_id);
